carts/urls.py
from django.urls import path
from .views import HomeView, ItemDetailView, add_to_cart, remove_from_cart, \
    OrderSummaryView, remove_single_item_from_cart, CheckoutView, PaymentView, \
    RequestRefundView, AddCouponView

app_name = 'carts'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('order_summary/', OrderSummaryView.as_view(), name='order_summary'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add_coupon'),
    path('remove_from_cart/<slug>/', remove_from_cart, name='remove_from_cart'),
    path('remove_single_item_from_cart/<slug>/', remove_single_item_from_cart, name='remove_single_item_from_cart'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('carts.urls', namespace='carts'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from datetime import datetime

from django.db.models.signals import post_save
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.db import models
from django_countries.fields import CountryField
from django.conf import settings

CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping')
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    title = models.CharField(max_length=256)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    discount_price = models.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2, default='S')
    label = models.CharField(choices=LABEL_CHOICES, max_length=1, default='P')
    slug = models.SlugField(default='test_item_slug')
    description = models.TextField(max_length=256, default='Test Description')
    img = models.ImageField(default=' ')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('carts:product', kwargs={'slug': self.slug})

    def get_add_to_cart_url(self):
        return reverse('carts:add-to-cart', kwargs={'slug': self.slug})

    def get_remove_from_cart_url(self):
        return reverse('carts:remove_from_cart', kwargs={'slug': self.slug})


class OrderItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.quantity} of {self.item.title}'

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        else:
            return self.get_total_item_price()


class Order(models.Model):
    items = models.ManyToManyField(OrderItem)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    billing_address = models.ForeignKey('Address', related_name='billing_address', on_delete=models.SET_NULL,
                                        blank=True, null=True)
    shipping_address = models.ForeignKey('Address', related_name='shipping_address', on_delete=models.SET_NULL,
                                         blank=True, null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey('Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    start_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True)
    ordered_date = models.DateTimeField(default=datetime.now)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    ordered = models.BooleanField(default=False)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)
    """
    1. Item added to cart
    2. Adding a billing address(Failed checkout)
    3. Payment(Prepossessing, processing, packages etc...)
    4. Being Delivered
    5. Received
    6. Refunds
    """

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=128)
    apartment_address = models.CharField(max_length=128)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=128)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Addresses'

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    stripe_charge_id = models.CharField(max_length=50)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.IntegerField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f'{self.pk}'


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <style type="text/css">
        html,
        body,
        header,
        .carousel {
            height: 60vh;
        }

        @media (max-width: 740px) {

            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }

        @media (min-width: 800px) and (max-width: 850px) {

            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }

    </style>
</head>
<body>
<!-- Navbar -->
{% include "navbar.html" %}
<!--/.Navbar -->

<div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
</div>

{% block content %}
{% endblock content %}

{% block extra_body %}
{% endblock %}

<!--Footer-->
{% include "footer.html" %}
<!--/.Footer-->

<!-- SCRIPTS -->
<!-- JQuery -->
{% include "scripts.html" %}
<!--/.SCRIPTS -->
<!--/.JQuery -->

{% block extra_scripts %}
{% endblock extra_scripts %}
</body>
</html>

templates/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">
    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
        <a href="https://www.facebook.com/mdbootstrap" target="_blank">
            <i class="fab fa-facebook-f mr-3"></i>
        </a>

        <a href="https://twitter.com/MDBootstrap" target="_blank">
            <i class="fab fa-twitter mr-3"></i>
        </a>

        <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
            <i class="fab fa-youtube mr-3"></i>
        </a>

        <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
            <i class="fab fa-google-plus-g mr-3"></i>
        </a>

        <a href="https://dribbble.com/mdbootstrap" target="_blank">
            <i class="fab fa-dribbble mr-3"></i>
        </a>

        <a href="https://pinterest.com/mdbootstrap" target="_blank">
            <i class="fab fa-pinterest mr-3"></i>
        </a>

        <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
            <i class="fab fa-github mr-3"></i>
        </a>

        <a href="http://codepen.io/mdbootstrap/" target="_blank">
            <i class="fab fa-codepen mr-3"></i>
        </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
        © 2019 Copyright:
        <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

</footer>

templates/home.html
{% extends "base.html" %}

{% block content %}
    <!--Main layout-->
    <main>
        <div class="container">
            <!--Navbar-->
            <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">
                <!-- Navbar brand -->
                <span class="navbar-brand">Categories:</span>
                <!-- Collapse button -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Collapsible content -->
                <div class="collapse navbar-collapse" id="basicExampleNav">
                    <!-- Links -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">All
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Shirts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Sport wears</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Outwears</a>
                        </li>

                    </ul>
                    <!-- Links -->
                    <form class="form-inline">
                        <div class="md-form my-0">
                            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                        </div>
                    </form>
                </div>
                <!-- Collapsible content -->
            </nav>
            <!--/.Navbar-->

            <!--Section: Products v.3-->
            <section class="text-center mb-4">
                <!--Grid row-->
                <div class="row wow fadeIn">
                    <!--Grid column-->
                    {% for item in items %}
                        <div class="col-lg-3 col-md-6 mb-4">
                            <!--Card-->
                            <div class="card">
                                <!--Card image-->
                                <div class="view overlay">
                                    <img src="{{ item.img.url }}" alt="" class="card-img-top" style="width: 300px;height: 300px">
                                    <a href="{{ item.get_absolute_url }}">
                                        <div class="mask rgba-white-slight"></div>
                                    </a>
                                </div>
                                <!--Card image-->
                                <!--Card content-->
                                <div class="card-body text-center">
                                    <!--Category & Title-->
                                    <a href="" class="grey-text">
                                        <h5>{{ item.get_category_display }}</h5>
                                    </a>
                                    <h5>
                                        <strong>
                                            <a href=""
                                               class="dark-grey-text">{{ item.title }}
                                                <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                                            </a>
                                        </strong>
                                    </h5>
                                    <h4 class="font-weight-bold blue-text">
                                        <strong>$
                                            {% if item.discount_price %}
                                                {{ item.discount_price }}
                                            {% else %}
                                                {{ item.price }}
                                            {% endif %}
                                        </strong>
                                    </h4>
                                </div>
                                <!--Card content-->
                            </div>
                            <!--Card-->
                        </div>
                    {% endfor %}
                    <!--Grid column-->
                </div>
                <!--Grid row-->
            </section>
            <!--Section: Products v.3-->

            <!--Pagination-->
            {% if is_paginated %}
                <nav class="d-flex justify-content-center wow fadeIn">
                    <ul class="pagination pg-blue">
                        <!--Arrow left-->
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                                   aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>
                        {% endif %}

                        <li class="page-item active">
                            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>

                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
            <!--Pagination-->
        </div>
    </main>
    <!--Main layout-->
{% endblock content %}

templates/navbar.html
{% load cart_template_tags %}
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

        <!-- Brand -->
        <a class="navbar-brand waves-effect" href="{% url 'carts:home' %}">
            <strong class="blue-text">DJ e-commerce</strong>
        </a>

        <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Left -->

            <ul class="navbar-nav mr-auto">
                {% comment %}
                <li class="nav-item active">
                    <a class="nav-link waves-effect" href="{% url 'carts:home' %}">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'carts:checkout' %}">Checkout</a>
                </li>
                {% endcomment %}
            </ul>


            <!-- Right -->
            <ul class="navbar-nav nav-flex-icons">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'carts:order_summary' %}">
                            <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
                            <i class="fas fa-shopping-cart"></i>
                            <span class="clearfix d-none d-sm-inline-block"> Cart </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
                            <span class="clearfix d-none d-sm-inline-block"> Logout </span>
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'account_login' %}">
                            <span class="clearfix d-none d-sm-inline-block"> Login </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
                            <span class="clearfix d-none d-sm-inline-block"> SingUp </span>
                        </a>
                    </li>
                {% endif %}
            </ul>

        </div>

    </div>
</nav>

templates/order_snippet.html
<div class="col-md-12 mb-4">

    <!-- Heading -->
    <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>

    <!-- Cart -->
    <ul class="list-group mb-3 z-depth-1">
        {% for order_item in order.items.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                    <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title }}</h6>
                    <small class="text-muted">{{ order_item.item.description }}</small>
                </div>
                <span class="text-muted">${{ order_item.get_final_price }}</span>
            </li>
        {% endfor %}
        {% if order.coupon %}
            <li class="list-group-item d-flex justify-content-between bg-light">
                <div class="text-success">
                    <h6 class="my-0">Promo code</h6>
                    <small>{{ order.coupon.code }}</small>
                </div>
                <span class="text-success">-${{ order.coupon.amount }}</span>
            </li>
        {% endif %}
        <li class="list-group-item d-flex justify-content-between">
            <span>Total (USD)</span>
            <strong>${{ order.get_total }}</strong>
        </li>

    </ul>
    <!-- Cart -->

    <!-- Promo code -->
    {% if DISPLAY_COUPON_FORM %}
        <form class="card p-2" action="{% url 'carts:add_coupon' %}" method="POST">
            {% csrf_token %}
            <div class="input-group">
                {{ couponform.code }}
                <div class="input-group-append">
                    <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
                </div>
            </div>
        </form>
    {% endif %}
    <!-- Promo code -->

</div>

templates/order_summary.html
{% extends "base.html" %}

{% block content %}
    <!--Main layout-->
    <main>
        <div class="container">
            <div class="table-responsive text-nowrap">
                <h2>Order Summary</h2>
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Item title</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total Item Price</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order_item in object.items.all %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ order_item.item.title }}</td>
                            <td>{{ order_item.item.price }}</td>
                            <td>
                                <a href="{% url 'carts:remove_single_item_from_cart' order_item.item.slug %}"><i
                                        class="fas fa-minus mr-2"></i></a>
                                {{ order_item.quantity }}
                                <a href="{% url 'carts:add-to-cart' order_item.item.slug %}"><i
                                        class="fas fa-plus ml-2"></i></a>
                            </td>
                            <td>
                                {% if order_item.item.discount_price %}
                                    ${{ order_item.get_total_discount_item_price }}
                                    <span class="badge badge-primary">(Saving ${{ order_item.get_amount_saved }})</span>
                                {% else %}
                                    ${{ order_item.get_total_item_price }}
                                {% endif %}
                                <a style='color: red;' href="{% url 'carts:remove_from_cart' order_item.item.slug %}">
                                    <i class="fas fa-trash float-right"></i>
                                </a>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="5">Your Cart is Empty</td>
                        </tr>
                        <tr>
                            <td colspan="5">
                                <a class="btn btn-primary float-right" href="{% url 'carts:home' %}">Proceed to
                                    Continue Shopping</a>
                            </td>
                        </tr>
                    {% endfor %}
                    {% if object.coupon %}
                        <tr>
                            <td colspan="4"><b>Coupon</b></td>
                            <td><b>${{ object.coupon.amount }}</b></td>
                        </tr>
                    {% endif %}
                    {% if object.get_total %}
                        <tr>
                            <td colspan="4"><b>Order Total</b></td>
                            <td><b>${{ object.get_total }}</b></td>
                        </tr>
                        <tr>
                            <td colspan="5">
                                <a class="btn btn-warning float-right ml-2" href="{% url 'carts:checkout' %}">Proceed to
                                    Checkout</a>
                                <a class="btn btn-primary float-right" href="{% url 'carts:home' %}">Proceed to
                                    Continue Shopping</a>
                            </td>
                        </tr>
                    {% endif %}
                    </tbody>
                </table>

            </div>
        </div>
    </main>
    <!--Main layout-->
{% endblock content %}

templates/product.html
{% extends "base.html" %}

{% block content %}
    <!--Main layout-->
    <main class="mt-5 pt-4">
        <div class="container dark-grey-text mt-5">

            <!--Grid row-->
            <div class="row wow fadeIn">

                <!--Grid column-->
                <div class="col-md-6 mb-4">

                    <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg"
                         class="img-fluid" alt="">

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-4">

                    <!--Content-->
                    <div class="p-4">

                        <div class="mb-3">
                            <a href="">
                                <span class="badge purple mr-1">{{ item.get_category_display }}</span>
                            </a>
                        </div>

                        <p class="lead">
                          <span class="mr-1">
                            <del>$
                                {% if item.discount_price %}
                                    {{ item.discount_price }}
                                {% else %}
                                    {{ item.price }}
                                {% endif %}
                            </del>
                          </span>
                            <span>${{ item.price }}</span>
                        </p>

                        <p class="lead font-weight-bold">Description</p>

                        <p>{{ item.description }}.</p>

                        {% comment %}<form class="d-flex justify-content-left">
                            <!-- Default input -->
                            <input type="number" value="1" aria-label="Search" class="form-control"
                                   style="width: 100px">
                            <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                                <i class="fas fa-shopping-cart ml-1"></i>
                            </button>

                        </form>{% endcomment %}

                        <a href="{{ item.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
                            Add to cart
                            <i class="fas fa-shopping-cart ml-1"></i>
                        </a>
                        <a href="{{ item.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
                            Remove from cart
                        </a>
                    </div>
                    <!--Content-->

                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->

            <hr>

            <!--Grid row-->
            <div class="row d-flex justify-content-center wow fadeIn">

                <!--Grid column-->
                <div class="col-md-6 text-center">

                    <h4 class="my-4 h4">Additional information</h4>

                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta
                        odit
                        voluptates,
                        quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->

            <!--Grid row-->
            <div class="row wow fadeIn">

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">

                    <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg"
                         class="img-fluid" alt="">

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                    <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg"
                         class="img-fluid" alt="">

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                    <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg"
                         class="img-fluid" alt="">

                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->

        </div>
    </main>
    <!--Main layout-->
{% endblock content %}

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
    <main>
        <div class="container">

            <h2>Request Refund</h2>
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button type='submit' class='btn btn-primary'>Submit</button>
            </form>

        </div>
    </main>

{% endblock content %}

templates/scripts.html
{% load static %}

<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
    // Animations initialization
    new WOW().init();

</script>